name: Release

on:
  workflow_dispatch:

  push:
    tags: ["v*"]

jobs:
  release:
    strategy:
      matrix:
        GOOS: [linux]
        GOARCH: [amd64]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '~1.17.13'

      - shell: bash
        run: |
          GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@v0.57.2
          builder --config=otelcol-builder.yaml --name=otelcol-pano-ec_${{ matrix.GOOS }}_${{ matrix.GOARCH }}

      - uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: dist/otelcol-pano-ec*