name: Release

on:
  workflow_dispatch:

  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - shell: bash
        run: |
          GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@v0.37.0

          # Static linking
          export CGO_ENABLED=0
          builder --config=otelcol-builder.yaml --name=otelcol-pano-ec

      - uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: dist/otelcol-pano-ec